### ISSUE TITLE
Quoted Bools still being generated

### ISSUE THREAD

**Issue by RichardCrawshaw** [david284/ModuleDescriptor#13]
In the most recent set of changes (2024-04-20) the fix for quoted Booleans has been reverted.

There probably needs to be some tests that can be performed as part of the PR and Merge processes through GitHub Actions to prevent this type of error being introduced in future.

**Comment by david284** [comment]
I realised the generators that can be used to create these files still had some quoted values - I wrongly thought they'd all been changed - corrected now
