### ISSUE TITLE
Typo dtartBit for startBit

### ISSUE THREAD

**Issue by RichardCrawshaw** [david284/ModuleDescriptor#8]
There is a typo in the following JSON files
* CANACC5-A502-2u.json
* CANACC5-A502-2V.json
* CANACC8-A503-2v.json
* CANBIP-OUT-A535-5b.json
* CANMIO-OUT-A534-5b.json

"dtartBit" instead of "startBit". Those files also contain correct instances.

**Comment by david284** [comment]
Thanks - I'll look at correcting those

**Comment by RichardCrawshaw** [comment]
I was planning on giving you a PR for those and the others I've raised. I had to fix them locally to proceed so it makes sense to push the changes and save you the effort.

**Comment by david284** [comment]
Yes, that'd be appreciated - NodeJS (and I suspect javascript in general) allowed me to wallow in my blissful ignorance of this - but checking ECMA-404, you're absolutely correct, quote marks should be reserved for strings
It's not the first time I've been caught out by Javascript allowing (and working) with things that a 'strongly typed' language like C# wouldn't allow
